w3c/coga

- issue-papers/math.html
Spelling and semantic structure revisions
> ACTION-168 Proofing Use of Numbers and Math on the Web

- issue-papers/payments.html
Major change - added introduction section including re-write of use case section. Additional minor editorial and link content changes also made.
> Updates to Payments.html at 2:45pm ET on 4-25-16

- issue-papers/graded-help.html
Implemented semantic outline. Reverted original content. Will make spelling and grammar changes without changing context or meaning with annotations to the group in the next pull request the week.
> Modifying graded-help.html

- issue-papers/flat-design.html
Fixed misspellings, changed heading structure to match other papers and indicated where more development is needed. Added in 2 new resource articles and a link that points to some research.
> Mary Jo branch

- issue-papers/task-completion.html
Previous version included distractions
> Content is focused on emotional disabilities

- extension/timed-events.html
The purpose of this commit is to ensure correct usage of the SC template. Authoring is in progress and not yet complete.
> Timed Events - Initial Draft/WIP

- extension/timed-events.html
- Modifications to WCAG 2.2.1 Timing Adjustable
- Updated What Principle and Guideline the SC falls within
- Updated Description
- Updated Benefits
- Updated Related Resources
- Added Working Group Notes
> Including Timed Events into existing WCAG 2.2.1

- user-research/id.html
Noticed this while reading through
> Fix casing: USe -> Use

- extension/timed-events.html
- More robust examples added to Benefits section
- Benefits to multiple disabilities added including more examples of cognative use cases
- First pass at Techniques. These already exist as part of 2.2.1 - Timing Adjustable and most likely need modifications or additions
> Update to benefits and first pass at Techniques

- extension/minimize-errors.html
- First Draft
- Related Resources in next pull request
- Testability in next pull request
- Please confirm if Techniques should come from the original WCAG 2.0 SC 3.3.3 with additions and/or modificaitons
> Minimize User Errors - First Draft

- extension/timed-events.html
- Adding additional use case under Benefits
- Adding Techniques
> Adding and additional use case and Techniques

- extension/minimize-errors.html
- Added Techniques for COGA Techniques
- Added reference to usability studies in Benefits
- Added Testability but think it may be too general. Provide feedback on Testability please.
> Techniques and additional updates

- extension/timed-events.html
Current rawgit Version Did not include latest updates
> Current rawgit Version Did not include latest

- extension/accessible-authentication.html
I have put the content from the provided word doc into the template. It should be a direct copy and paste from the Word document. I am not the content author.
I have also emailed you the file. If you decide that you prefer the previous version please do not merge the pull request
> Mikes Updates

- extension/minimize-errors.html
Significant updates to Description
Updates to Benefits
> Minimize Errors - Description Update

- extension/timed-events.html
Added Testibility
Added content from original COGA Techniques Document
> Added Testibility

- extension/labels-instructions.html
- Testability will be included in next Pull Request
- Techniques will be included in next Pull Request
> Labels and Instructions Initial Draft

- extension/labels-instructions.html
- Techniques next pull request
- Testability next pull request
> First Update Based on Feedback

- extension/labels-instructions.html
- Testability in the next pull request tomorrow
> Update to Benefits and Techniques

- extension/return.html
- Last sentence of Benefits section - “It is part of the theme” - Not clear on the word “theme” is there another would that would be more clear
> Grammar and spelling updates

- extension/error-prevention-legal.html
- extension/help.html
- extension/labels-instructions.html
- extension/reminders.html
Please wait approximately one hour to approve
> Completing copyediting

- content-usable/index.html
good edits form edits
lisa updated terms (themes  _> objectives, and requirements to patterns) and editors notes and includes
> Content usable rbreview

- design/index.html
new pull request after merged in rachaels changes
> Fix a couple of pattern names

- design/index.html
[I'm working to a policy of any merge should be via a PR - @SteveALee ]
Changes to make the introduction more clear and some minor editorial fixes.
> Editorial Changes to design guide

- content-usable/README.md
- content-usable/design.html
edits that add in missing pieces to the patterns by rachael and me
> Edits to patterns jan 2020

- content-usable/design.html
Here's my changes for review
Some points to concider:
* I used Blockquote
* I used as personal short form style
* We could posisbly add a header for the quote and 'what to do'
[Content Usable preview for this PR](https://raw.githack.com/w3c/coga/pattern-stories/content-usable/index.html#pattern-make-the-purpose-of-your-page-clear)
[Diffs](https://github.com/w3c/coga/pull/104/files)
> Add user stories

- content-usable/design.html
- content-usable/index.html
This is an early PR so we can all easily track the work.
[Content Usable preview for this PR](https://raw.githack.com/w3c/coga/steve-misc-updates/content-usable/index.html)
[Source diffs](https://github.com/w3c/coga/pull/105/files)
Note: next two diffs are separate as HTMLDiffs doesn't run respec and so parse includes like the design guide.
[content-usable HTML diffs](https://services.w3.org/htmldiff?doc1=https%3A%2F%2Fraw.githack.com%2Fw3c%2Fcoga%2Fpre-csun-2020%2Fcontent-usable%2Findex.html&doc2=https%3A%2F%2Fraw.githack.com%2Fw3c%2Fcoga%2Fsteve-misc-updates%2Fcontent-usable%2Findex.html)
[design guide HTML diffs](https://services.w3.org/htmldiff?doc1=https%3A%2F%2Fraw.githack.com%2Fw3c%2Fcoga%2Fpre-csun-2020%2Fcontent-usable%2Fdesign.html&doc2=https%3A%2F%2Fraw.githack.com%2Fw3c%2Fcoga% …
> Steve misc updates

- content-usable/design.html
- content-usable/index.html
- content-usable/mapping-user-patterns.html
So far I've only reordered the patterns but comments are welcome
https://raw.githack.com/w3c/coga/steve-reordering/content-usable/index.html
Next up is the mapping to user needs
> Steve reordering

- content-usable/design.html
- content-usable/index.html
- content-usable/respec-config.js
Code quality fixes during review of wide review draft prep. Some of these are needed for the document to display as intended.
> MC code fixes

- glossary/index.html
Added agreed terms to the glossary file
> Update glossary definition

- content-usable/design.html
- content-usable/index.html
- content-usable/mapping-user-patterns.html
add [part1 comparison](https://docs.google.com/document/d/10IQLt4ZVcy42s-J9G8QzJIP1EjTX03bLA3cZnCl98tE/edit?ts=5ff67049#) to content-usable in master branch
> Added part1 comparison to content-usable in master branch

- content-usable/design.html
- content-usable/index.html
These are the changes from the 25 January 2021 wordsmithing meeting. They address issues 119, 120, 122, and 123
> Changes from wording meeting

- content-usable/design.html
- content-usable/index.html
Changes from issues 117, 166, 181, 183, 184, 187, 189. Merge this before the google docs.
> Changes from issues

- content-usable/index.html
Added "key topics" to the first sentence of the summary
> Issue 118 Add "key topics" to summary

- content-usable/design.html
In response to issue 141, added the word "mathematics" in parenthesis after first usage in document.
> Add "Mathematics" in parens - issue 141

- content-usable/index.html
Fixing the broken close line item tag on line 211
> Update index.html to fix broken line item tag

- content-usable/index.html
Removing repeating word "cognitive" in the summary, "Support adaptation and personalization"
> Update index.html - remove double "cognitive"

- content-usable/design.html
Fixing a typo under 4.3.5.4 More Details
> Update design.html - fix typo in 4.3.5.4

- content-usable/design.html
Fixing misplaced p tag in 4.5 Objective 4: Help Users Avoid Mistakes and Know How To Correct Them
> Update design.html - misplaced p tag in 4.5 objective 4

- content-usable/design.html
Fixing a couple typos in 4.5.4.4 More Details
> Update design.html fixing typos in 4.5.4.4 More Details

- content-usable/design.html
Fixing typos in 4.5.9.3 How it Helps
> Update design.html - typos in 4.5.9.3 How it Helps

- content-usable/design.html
Fixing a typo in 4.5.6.4 More Details
> Update design.html - fixing a typo in 4.5.6.4 More Details

- content-usable/design.html
Removing extra word in 4.5.9.5 Examples
> Update design.html - removing extra word in 4.5.9.5

- content-usable/design.html
> Update design.html - typos in 4.6.4.3

- content-usable/design.html
> Update design.html - typo in 4.7.2.2

- content-usable/design.html
adding missing period in 4.7.3.3 How it Helps
> Update design.html - missing period in 4.7.3.3 How it Helps

- content-usable/design.html
Removing unintentional characters under 4.9.1.3 How it Helps
> Update design.html - unintentional characters under 4.9.1.3 How it Helps

- content-usable/design.html
Removing unintentional characters and adding code markup under 4.9.3.5 Getting Started, removing extra word under 4.9.3.6
> Update design.html - unintentional characters and other edits, 4.9.3.5 Getting Started

- usable-prototype/index-prototype2.html
- File(s) added/changed: index-prototype2.html
- Short description of changes: updating the content for the prototype so that Roy can focus on the technical fixes
##Source
- where is it from such as google docs url : [----](https://docs.google.com/document/d/1SJHitx9MRQBz9UDZH2olclf0tc9_Zm6Of5vSAjaQ_0U/edit)
- [ x] No
- Added content
- [x ]  I checked the stucture is the same as the original
- [x ]  I checked the format is the same as the original 
- [x ]  pargraph before and after loads corectly without changes to the font or format
> Rain's content updates

- design-guide/o1p01-clear-purpose.html
- design-guide/o2p02-site-structure.html
- File(s) added/changed: ---- Proposal 2
- Short description of changes: ----
- Notes (if needed): ----
##Source
- where is it from such as google docs url : ----
- when was it aproved such as meating minutes : ----
> Mh proposal1
